E2Helper.Descriptions["navCanPathFind()"] = "Checks if it hasn't been too recent since your previous pathfind"
E2Helper.Descriptions["navSetStepHeight(n)"] = "Set height the follower can step up on"
E2Helper.Descriptions["navSetFallHeight(n)"] = "Set height the follower will avoid falling from"
E2Helper.Descriptions["navSetSlopeLimit(n)"] = "Set slope angle limit the follower can walk on"
E2Helper.Descriptions["navSetFollowerSize(n)"] = "Set width follower can fit through"
E2Helper.Descriptions["navSetFollowerHeight(n)"] = "Set height follower can step under"
E2Helper.Descriptions["navSetNextPointDist(n)"] = "Set distance where a point will be ignored and go to next one"
E2Helper.Descriptions["navCreatePatherSimple()"] = "Create a path manager that handles path generation"
E2Helper.Descriptions["navBeginPathSimple(vv)"] = "Begin setup for path generation from first vector to second vector"
E2Helper.Descriptions["navPathStepSimple(n)"] = "Perform n number of steps in path generation"

